### ISSUE TITLE
A useless parameter was found

### ISSUE THREAD

**Issue by godofgeek** [teo-sl/DPLAN_pytorch#2]
Is the initialization parameter c in DPLAN.py useless and can be removed?

**Comment by teo-sl** [comment]
Yes :)

**Comment by godofgeek** [comment]
self.index_n=np.where(self.y==2)[0] .What does this code do? Labels are only 0 and 1 ，no label was found as 2.Please give an answer.

**Comment by teo-sl** [comment]
It's an improvement of the original paper. If we have the knowledge of some anomalies it is reasonable to assume that we can also know a certain number of normal data point (so, "2" is the label for normal datas, index_n: index of normal data). If you want to use this approach you need to add these labels in the dataset, as you can see in the preprocessing file. Otherwise you need to do some changes in the code.

**Comment by godofgeek** [comment]
Doesn't 0 mean a normal instance?

**Comment by teo-sl** [comment]
In an anomaly detection scenario in 0 we have both normal data and anomalies (in a very little percentage). Starting from the original dataset you take a small subset of anomalies (only from a particular anomaly class in Pang et al.) and you give them the label "1". Then, the rest of the dataset is labeled as "0". I took a little subset of ""real"" normal data and changed its label from 0 to 2. Hope this helps

**Comment by godofgeek** [comment]
I'm sorry, I didn't quite get it.Where is the source of the data?Is the data in this link usable?https://www.kaggle.com/datasets/dhoogla/unswnb15/data

**Comment by teo-sl** [comment]
The original website I used is no longer available, but I think this version is pretty much the same: https://www.kaggle.com/datasets/mrwellsdavid/unsw-nb15. You first need to preprocess the dataset using the script in the preprocessing dir.

**Comment by godofgeek** [comment]
Thank you. I'll try
